title: My theme trial
project: hello_worlds
# description: build a site with the cayman theme
description: build a site with the minimal-mistakes theme
markdown: kramdown

# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: mmistakes/minimal-mistakes@4.26.2

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
